export declare function rm(selector: string, all: boolean | undefined, dom: HTMLElement): void;
export declare function rm2(filters: (string | RegExp)[], dom: HTMLElement): void;
export declare function rms(filters: (string | RegExp)[], dom: HTMLElement): HTMLElement;
export declare function childNodesCopy(src: Element, dest: Element): void;
export declare function getMaxDepth(element: Element): number;
export declare function getNodeTextLength(element: Element): number;
export declare function sandboxed(code: string): any;
export declare function getCookie(name: string): string | null;
export declare function createEl(el: string): HTMLElement;
export declare function createStyle(style: string, id?: string): HTMLElement;
export declare function getNextSibling(node: Element | Text): ChildNode | null | undefined;
export declare function getPreviousSibling(node: Element | Text): ChildNode | null | undefined;
export declare function getPreviousBrCount(node: Element | Text): number;
export declare function removePreviousBr(node: Element | Text): void;
export declare function fullWidthLength(input: string): number;
export declare function convertHTMLtoXHTML(input: string | Document): string;
export declare function insertBrBeforeText(elem: HTMLElement): void;
export declare function isHidden(el: HTMLElement): boolean;
export declare function escapeHTML(str: string): string;
