/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/cookies': RouteRecordInfo<'/cookies', '/cookies', Record<never, never>, Record<never, never>>,
    '/download': RouteRecordInfo<'/download', '/download', Record<never, never>, Record<never, never>>,
    '/overview': RouteRecordInfo<'/overview', '/overview', Record<never, never>, Record<never, never>>,
    '/resume': RouteRecordInfo<'/resume', '/resume', Record<never, never>, Record<never, never>>,
    '/rules/': RouteRecordInfo<'/rules/', '/rules', Record<never, never>, Record<never, never>>,
    '/rules/[rule]/setting': RouteRecordInfo<'/rules/[rule]/setting', '/rules/:rule/setting', { rule: ParamValue<true> }, { rule: ParamValue<false> }>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
  }
}
