name: Bug报告
description: 填写一个BUG报告
title: "[Bug]: "
body:
  - type: checkboxes
    id: Prerequisites
    attributes:
      label: 必要条件
      description: |
        为了减少无效报告，请确认每一个选项。
      options:
        - label: 我已经搜索 issue 区，并确定没有相同问题存在。
          required: true
        - label: 我已经尝试将脚本升级至最新版本，但问题仍存在。
          required: true
        - label: 在尝试下载付费章节前，我已经购买了相应付费章节。
          required: true

  - type: checkboxes
    id: reproduce_checkboxes
    attributes:
      label: 当我尝试复现issue时……
      options:
        - label: 我使用的浏览器是最新版 Chrome 或 Firefox
        - label: 脚本管理器（Tampermonkey/Violentmonkey）是唯一浏览器插件
        - label: 小说下载器脚本是唯一用户脚本

  - type: textarea
    id: Description
    attributes:
      label: 问题描述
      description: 请具体描述你所遇到的问题。
    validations:
      required: true

  - type: input
    id: issue_url
    attributes:
      label: 问题发生的网址：
      description: 一个可以复现issue的网址。
    validations:
      required: true

  - type: textarea
    id: Steps_to_Reproduce
    attributes:
      label: 复现步骤
      placeholder: |
        1. [第一步]
        2. [第二步]
        3. [and so on...]
    validations:
      required: true

  - type: textarea
    id: Expected_behavior
    attributes:
      label: 期待的行为
      description: 你期待发生什么
    validations:
      required: true

  - type: textarea
    id: Actual_behavior
    attributes:
      label: 实际的行为
      description: 实际发生了什么，请在此附上日志。(请上传文件)
    validations:
      required: true

  - type: input
    id: script_version
    attributes:
      label: 小说下载器脚本版本
    validations:
      required: true

  - type: input
    id: script_handler_version
    attributes:
      label: 脚本管理器（Tampermonkey/Violentmonkey）版本
    validations:
      required: true

  - type: input
    id: browser_name_and_version
    attributes:
      label: 浏览器名称及版本
    validations:
      required: true
