name: 新功能请求
description: 填写一个新功能请求
title: "[Feature Request]: "
body:
  - type: checkboxes
    id: Prerequisites
    attributes:
      label: 必要条件
      description: |
        为了减少无效报告，请确认每一个选项。
      options:
        - label: 我已经搜索 issue 区（包含已关闭的 issue），并确定没有相同的请求存在。
          required: true
        - label: 我已经仔细阅读了最新的 readme 文档，确认文档中没有包含新功能的描述。
          required: true
  - type: textarea
    id: Problem
    attributes:
      label: 存在问题
      description: 请具体描述你认为脚本目前存在的问题。
    validations:
      required: true
  - type: textarea
    id: Aim
    attributes:
      label: 目标愿景
      description: 希望脚本实现的功能/目标。
    validations:
      required: true
  - type: textarea
    id: Reference
    attributes:
      label: 参考建议
      description: 可以供参考的建议
    validations:
      required: false
  - type: textarea
    id: Supplement
    attributes:
      label: 补充内容
      description: 其他补充内容
    validations:
      required: false