export declare const environments: () => Promise<{
    当前时间: string;
    当前页URL: string;
    workerId: string;
    当前页Referrer: string;
    浏览器UA: string;
    浏览器语言: readonly string[];
    设备运行平台: string;
    设备内存: any;
    CPU核心数: number;
    eval: string;
    fetch: string;
    XMLHttpRequest: string;
    streamSupport: boolean;
    window: number;
    localStorage: any;
    sessionStorage: any;
    Cookie: boolean;
    doNotTrack: string | number;
    ScriptHandler: string;
    "ScriptHandler version": string;
    "Novel-downloader version": string;
    enableDebug: boolean;
    jsdelivr: unknown;
}>;
